language: java
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
      - harrygallagher4@gmail.com
    on_failure: always
    on_success: never
addons:
  artifacts:
    provider: s3
    permissions: public
