language: java
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
      - harrygallagher4@gmail.com
    on_failure: always
    on_success: never
addons:
  artifacts:
    debug: true
    bucket: me.hgal.event
    cache_control: private
    permissions: public
